### ISSUE TITLE
Triage of the Generative Suggestions

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#17]
Relevant to other issues (e.g. #15) but a specific question related to the large numbers of molecules arising from the @kipUNC generative methods. **How do we triage suggestions?**

1) Kostya mentioned that filters can be trivially applied. It seems to me that we want to be able to move beyond fragments, and still have decent solubility for soaking experiments if needed. So shall we apply a filter to say that the _molecules need to be to least 3 heavy atoms heavier than the original fragments_? Roughly what range does that give, if we say that the MW is 40-60 higher than the compounds that were found to bind? _And let's say logP under 3_?

2) Kostya thinks that we may make it more likely that the suggestions are purchaseable if we focus on the structures that are common to all output libraries. He suggests looking for 10 random molecules (after we've triaged as above) that are *not* common to all libraries, but which are unique to the e.g. Chembl-trained library.

3) Once picked, let's have them all docked for reasonableness.

If agree (?), we can ask Kostya to apply the filter and come up with new suggestions.

**Comment by drc007** [comment]
@mattodd @kipUNC How many is a "large number of molecules"?

I can search for commercial availability if less than 100K molecules.

**Comment by TomkUCL** [comment]
The average molecular weight of the initial fragments from issue #2 is 209, so I have set the fragments that we are looking for from libraries A, C, and E between MW = 229 to 269, and logP less than 3. Data warrior allows these filters to be put in as sliding scales which can also be changed as required.

![image](https://user-images.githubusercontent.com/92033163/154060377-95b0712b-fb2c-44f1-9ecd-73744e62b383.png)
![image](https://user-images.githubusercontent.com/92033163/154064476-6cf7c8bc-faf1-42ae-8e9b-c87f4e5a5407.png)

I've used the data warrior sliding scales to select for molecular weight and logP values described above using the following pathway: Chemistry > From Chemical Structure > Calculate Properties... > select 'Total average molweight in g/mol', 'cLogP'

[Library_A_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069098/Library_A_hits.triaged.zip)
[Library_C_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069099/Library_C_hits.triaged.zip)
[Library_E_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069101/Library_E_hits.triaged.zip)

Library A ( ): 99 compounds 
Library C ( ): 233 compounds 
Library E ( ): 92 compounds

**Comment by TomkUCL** [comment]
@drc007 Do you have any recommendations regarding how best to search these lists for commercial availability? I see that datawarrior has built-in Search Enamine Building Blocks, but i'm not sure whether this is suitable for this many compounds. Thanks!

**Comment by TomkUCL** [comment]
> @TomkUCL If you send me a list of structures (as sdf or SMILES) I can search them for you. Cheers, Chris

Thanks Chris, here are the SMILES lists: 

[Libraries A C E triaged hits SMILES.xlsx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8107497/Libraries.A.C.E.triaged.hits.SMILES.xlsx)

**Comment by drc007** [comment]
@TomkUCL Annotated with vendor info.
[LibraryEvendors.csv](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8108195/LibraryEvendors.csv)
[LibraryCvendors.csv](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8108196/LibraryCvendors.csv)
[LibraryAvendors.csv](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8108197/LibraryAvendors.csv)

**Comment by drc007** [comment]
@TomkUCL Row 1 is all the suppliers that claim to have a least 1 of the compounds in stock.

**Comment by TomkUCL** [comment]
@drc007 Sorry, I'm not familiar with all of these vendors. I have interpreted the list so that those SMILES with no vendor codes beyond column B (InChIKey) I am assuming are commercially unavailable, which I have highlighted so that you get something looking like this... 
![image](https://user-images.githubusercontent.com/92033163/155527431-c3dbb6dc-af4b-4f32-bffb-43a0f6b10f72.png)

Is this correct?

**Comment by drc007** [comment]
@TomkUCL I've only included vendor codes for those compounds that are "in stock".  For some compounds with no vendor codes there may be a ZINC ID or PubChem ID that can be used to identify sources that can make a compound if ordered. The vendors are all named and detailed here https://zinc.docking.org/catalogs/ 

Vendors like eMolecules, Mcule Molport aggregate multiple catalogues and act as a intermediary. If you focus on these vendors it often saves time.

**Comment by TomkUCL** [comment]
@drc007 Brilliant, thanks!

**Comment by TomkUCL** [comment]
I have run a quick Mcule search of the 99 SMILES from LibraryAvendors, which threw back a couple of results at $175 + $179 shipping... 

![image](https://user-images.githubusercontent.com/92033163/155538316-690ba569-bf59-41c6-aef7-5615bf79e36c.png)

**Comment by TomkUCL** [comment]
@kipUNC Here are the SMILES lists of compounds from libraries A, C and E (ChEMBL trained):
[Library A chemspace-search.xlsx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8142160/Library.A.chemspace-search.xlsx)
Note the SMILES doesn't seem to be regioselective for alkenes, so both regioisomers (E/Z) are included in the SMILES. 

I have generated these lists by inserting the LibraryAvenors.csv, LibraryCvenors.csv, and LibraryEvenors.csv files described above from Chris into Data Warrior as a similarity chart shown below here:
![image](https://user-images.githubusercontent.com/92033163/155737180-33b647c2-57dc-4cfb-9437-043b35a95201.png)

I then selected 30 compounds from each library (A through E), choosing both compounds from clusters (those with similar structures) as well as some outliers to try and maximise the chemical space represented by these fragments:
![image](https://user-images.githubusercontent.com/92033163/155738342-9d5e3d31-3f18-4601-8fdb-757d1c651902.png)
Finally, I ran these SMILES through a final commercial search on Chemspace to generate the final list below of compounds for docking given. Those in green are listed as cheap (i.e. <$100 per 1 mg), so you can exclude those if you wish. 

Does this work ok with you? If so then I will also upload the same lists for Libraries C and E here shortly.

**Comment by TomkUCL** [comment]
> @mattodd @kipUNC The average molecular weight of the initial fragments from issue #2 (pictured below) is 209, so I have set the fragment filters that we are looking for from libraries A, C, and E to MW = 249 to 269, and logP less than 3. Data warrior allows these filters to be put in as sliding scales which can also be changed as required.
> 
> ![image](https://user-images.githubusercontent.com/92033163/154060377-95b0712b-fb2c-44f1-9ecd-73744e62b383.png) ![image](https://user-images.githubusercontent.com/92033163/154064476-6cf7c8bc-faf1-42ae-8e9b-c87f4e5a5407.png)
> 
> I've used the data warrior sliding scales to select for molecular weight and logP values described above using the following pathway: Chemistry > From Chemical Structure > Calculate Properties... > select 'Total average molweight in g/mol', 'cLogP', then simply type in the selected range values for each scale.
> 
> [Library_A_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069204/Library_A_hits.triaged.zip) [Library_C_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069205/Library_C_hits.triaged.zip) [Library_E_hits triaged.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8069206/Library_E_hits.triaged.zip)
> 
> **Library A** ( Pre-trained on ChEMBL, Hits from filtered, unbiased model using pharmacophore scoring function): **99 compounds.** **Library C** ( Pre-trained on ChEMBL, Use Library B to fine-tune generative model): **182 compounds.** **Library E** (Pre-trained on ChEMBL Reinforcement learning using pharmacophore scoring function): **74 compounds.**

**UPDATE:**

Ok, here are the SMILES @kipUNC. I took the Library A,C and E triaged dw files above, selected 30 structures whilst trying to maximise the chemical space explored in each one and then submitted those through ChemSpace. Some are commercially available, and these are described in the document below. 

[Triaged commercial vendors similarity chart.docx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8142879/Triaged.commercial.vendors.similarity.chart.docx)

**Comment by mattodd** [comment]
Great work @TomkUCL! If @kipUNC can dock the lot then we can select 10 from each library to make, and maybe some to buy.

**Comment by kipUNC** [comment]
Thank you! I will provide the scores by Tuesday.

**Comment by TomkUCL** [comment]
@kipUNC @H-agha What is the PDB code of the apo state protein that you are docking to? I will try to get some scores in ICM pro as well.

**Comment by H-agha** [comment]
> @kipUNC @H-agha What is the PDB code of the apo state protein that you are docking to? I will try to get some scores for these fragments in ICM pro as well.

I used the PDB for fragment 420 - (PDB ID: 5RM6). However, after we learned from Jo about the electron density (ED) of the soaked crystals. I am not sure if it is better to use other crystal structures such as (PDB:5RMJ) for fragment  645 or (PDB: 5RMG) for fragment 524. Both fragments showed better ED map.

**Comment by mattodd** [comment]
Hi @H-agha so wait, you mean for the docking of the potentials (above), or do you mean a more fundamental re-assessment of the pharmacophore/design? Please can you elaborate?

**Comment by kipUNC** [comment]
I do not think we should worry about that. 420 is still good for docking, at least as good as any other. The electron densities of the ligands are not of a concern here.

**Comment by H-agha** [comment]
Agha, Hebaalla has shared a OneDrive for Business file with you. To view it, click the link below.
<https://adminliveunc-my.sharepoint.com/personal/hebaa_ad_unc_edu/Documents/Attachments/Site%203-%20Fragm%20_%20residues%20alignment.zip>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://adminliveunc-my.sharepoint.com/personal/hebaa_ad_unc_edu/Documents/Attachments/Site%203-%20Fragm%20_%20residues%20alignment.zip>
Site 3- Fragm _ residues alignment.zip<https://adminliveunc-my.sharepoint.com/personal/hebaa_ad_unc_edu/Documents/Attachments/Site%203-%20Fragm%20_%20residues%20alignment.zip>

I am not able to attach the video on GitHub. So, I am sending it here.

________________________________

**Comment by kipUNC** [comment]
It is always a trade off, so we either dock into all structures or use one and keep other in mind when do final hit evaluation. The electron densities of the fragments do not change anything about binding site selection at this point.

**Comment by mattodd** [comment]
Okeydoke @TomkUCL - @kipUNC has done some _Glide magic_ and come up with top 30 per library in [these two sheets](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/tree/main/FIle%20Diary/2022/Mar%202022/Konstantin%20Library%20Ranking) (one is the code cross-reference, the other are the scores). I think the two questions are
1) Which library is seemingly performing better? (maybe colour code the sheet?)
2) How many of the top 30 are commercial vs need to be made. In an ideal world we'd have a mix of things we can order and things we can make. Can you make a Chemdraw sheet that shows that - maybe start with the top 30 and see what proportion needs to be made/bought? Again, maybe colour code somehow and indicate ones that can be bought with a clearly highlighted price or supplier?

**Comment by TomkUCL** [comment]
In terms of which library is the best scoring, it doesn't look clear cut to me. In the top 30 scoring compounds we have: 
Library A = 11 fragments 
Library C = 8 fragments
Library E = 11 fragments 

[Kosta.dock.list.1.xlsx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8179747/Kosta.dock.list.1.xlsx)

![image](https://user-images.githubusercontent.com/92033163/156619420-b204cf0c-53c4-465e-8ad6-83ce3d678165.png)

A quick ChemSpace search is summarised here, I will summarise this in a ChemDraw for tomorrow's meeting. 
[chemspace-search-20220303191749.xlsx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8179757/chemspace-search-20220303191749.xlsx)

**Comment by H-agha** [comment]
Attached is the comparison of the docking scores for 3 different trials.
[Library A-C-E docking scores- comparison.xlsx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8186489/Library.A-C-E.docking.scores-.comparison.xlsx)

**Comment by TomkUCL** [comment]
Here is a list of commercial and non-commercial fragments and some early thoughts on synthetic steps. Sorry took longer than expected as a lot of these were showing up through manual searches but not through Chemspace. I will continue to add to the synthetic routes for non-commercial fragments. 

[Kosta docked top 30 fragments.docx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8214229/Kosta.docked.top.30.fragments.docx)

**Comment by mattodd** [comment]
Really good analysis @TomkUCL. How about we work our way through it on Friday to ID the compounds that we should obviously order, those we should obviously make, and then then ones in the grey area. I guess the grey area ones are those where we might reconsider if the modeling is not strongly supportive.

**Comment by TomkUCL** [comment]
No problem, happy to go through these tomorrow. I was hoping to have these docked today in ICM to back up some of Kosta and Heba's scores, but currently still waiting on the license renewal. I have been trying to install Autodock Vina as a backup, but there seem to be issues installing it on Windows, so i'll likely have to wait until ICM is back up and running.

**Comment by TomkUCL** [comment]
> @mattodd Here is a list of commercial and non-commercial fragments and some early thoughts on synthetic steps. Sorry took longer than expected as a lot of these were showing up through manual searches but not through Chemspace. I will continue to add to the synthetic routes for non-commercial fragments.
> 
> [Kosta.docked.top.30.fragments.docx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8224389/Kosta.docked.top.30.fragments.docx)

Starting materials for 15E, 3A, 2A, and 4A have been ordered to arrive this week. According to the literature, the planned synthesis is 1 step, approximately 15 mins reaction time, so hopefully, I should be able to get these 4 compounds made by the following week. 

I will compile a list of compounds that will need to be bought shortly.

**Comment by TomkUCL** [comment]
Hi @H-agha, 
I am trying to get some scores in AutoDock Vina for the top 30 fragment hits from Kosta's modelling to compare with the Glide scores that you have both generated (this is a slow process as I am also a first-time docker and self-teaching). I am using PyMol to prep the protein for docking as shown below. Can I just confirm with you that I have the correct site (site 3, https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/issues/2#issue-1027586728 on the protein? 

I have highlighted the residues (yellow) discussed for the original pharmacophore that you have generated. Am I correct in saying that this is away from the ligand (orange) site in PDB 5RM6 (pictured below)? I know that this is old news now, but this as much for my own understanding of the process as much as it is for getting the scores! 

![image](https://user-images.githubusercontent.com/92033163/158028980-f2bff991-ef81-479f-b7dc-754d7c074ea6.png)


Thanks! :)

**Comment by H-agha** [comment]
Hi @TomkUCL, Good try. I am sorry, I am not familiar with AutoDock Vina. I used only Schrodinger applications. So, I can not help with this software.

However, I have only one comment. The score of 15E using bigger grid (-6.9) is actually higher and better than the score of (-5.9) using smaller grid. The very negative score corresponds to a strong binding and a less negative or even positive score corresponds to a weak or non-existing binding.

**Comment by TomkUCL** [comment]
Thanks @H-agha . I am comfortable with the docking procedure now I think. 

So far I have been using a 20x20x20 grid centred around the residues specified in the pharmacophore. Maybe for conformity I will dock on Vina using the same grid dimensions so that we can get a direct comparison. 

Can I ask which coordinates your grid is centred at?

**Comment by H-agha** [comment]
I am not sure what you meant by (Can I ask which coordinates your grid is centred at?) - the default settings in Glide make the grid centered around the ligand when we pick its atoms and the software define the dimensions. The bigger one (15x15x19) was a suggestion from Kostya, I think he chose these numbers so that it can cover a ligand that is bigger than the fragments to include any possible new residues in the binding site and cover a bigger ligand binding site. Kostya (@kipUNC), please correct me if I am wrong.

**Comment by H-agha** [comment]
Hi all,
Looking at the binding modes of the best compounds and the nearby residues in the active site of site #3. I suggested some modifications to these compounds that can add more interactions with other residues in the binding site. 17 compounds showed better docking scores and new interactions.
FYI, I  still need to check the synthetic feasibility of these modifications. Here are the slides.
[Modified Structures -Library A, C, E_HA.pptx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8310502/Modified.Structures.-Library.A.C.E_HA.pptx)

**Comment by kipUNC** [comment]
Colleagues, please take a look at top 100 compounds from screening Enamine 40B library. Please double check for duplicates.
[nsp13_40bil_top_100.txt](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/8338969/nsp13_40bil_top_100.txt)

**Comment by kipUNC** [comment]
Ok here are two DataWarrior files:
1. clustering_struct_score_1000.dwar -- files where I clustered top 1000 compounds including multiple scores (multiple poses) for same compounds. This information can give us an idea if some compounds have multiple poses that score well. Maybe an indication of a "goodness" of the compound. Clusters/compounds are colored by the score, so we want more green. 
2.  cluster_centroids_100.dwar -- top 100 unique compounds with the scores. 

Ok doesn't look like I can attach dwar format here. e-mailing...

**Comment by H-agha** [comment]
Thanks, Kostya!
________________________________

**Comment by TomkUCL** [comment]
Thanks @kipUNC  - will look over this before monday's meeting!
