### ISSUE TITLE
Engaging covid-19 open science community on Just One Giant Lab

### ISSUE THREAD

**Issue by szackloo** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#18]
Dear All. This is a cool open science community who has interest and skills to contribute. https://app.jogl.io/need/697

**Comment by mattodd** [comment]
Thanks! I wonder what's the best way to ensure cross-talk between JOGL and OCN. e.g. updates to them about this and other OCN projects (do we need newsletters...?)

**Comment by szackloo** [comment]
good question mat. I created the OCN project on JOGL to draw the chemistry community to this gihub site. Thus the JOGL post for CNP4 links back to this github site. 
Similarly, I have been contacting SGC friends/family to request whether they would post Target 2035 initiatives including OCN. Tim Willson has offered to create a page here https://www.sgc-unc.org/ .
