### ISSUE TITLE
Initial Analysis of the site by Heba 

### ISSUE THREAD

**Issue by mattodd** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#2]
Hebaalla Agha (@H-agha) from UNC carried out the original analysis of the fragment cluster found to bind to this site (termed C-terminus-B in the original paper, colloquially internally referred to as Site 3).

The 2D and 3D interaction diagrams for all the fragments may be seen in [this Word file](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/Heba%20Initial%20Analysis%20of%20Interactions.docx) and [this powerpoint file](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/site%2016%20interactions%20comments_HA(1).pptx).

The relevant fragments are these:

<a href="url"><img src="https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/The%20fragments%20in%20question.png?raw=true" align="centre" height="400" ></a>

Strings: _need inserting_

This led to an initial pharmacophore suggestion from @H-agha:

<a href="url"><img src="https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/Pharmacophore%20suggestion.png?raw=true" align="centre" height="400" ></a>

and some suggested compounds that might be suitable.

<a href="url"><img src="https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/Initially%20Suggested%20Compounds.png?raw=true" align="centre" height="400" ></a>

Then @mattodd summarised the pharmacophore model and worked with @TomkUCL and @edwintse to come up with some initial suggestions for buying fragments and making others.

<a href="url"><img src="https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/blob/main/FIle%20Diary/2021/Sept/Site%2016%20Core%20and%20Suggestions.jpeg?raw=true" align="centre" height="400" ></a>

...thus completing the initial analysis. 

Question: are there better suggestions for elaborated fragments (i.e. things that should bind better) that are

1) commercially available, or
2) synthesiseable (not purchaseable) with low-to-medium effort?

(This page is now linked to on the wiki, so can be closed without orphaning.

**Comment by TomkUCL** [comment]
@H-agha are you able to upload your slides from todays nsp13 meeting please? We will begin looking at other linkers for molecule 1C as discussed in our meeting. Thanks. 
![image](https://user-images.githubusercontent.com/92033163/144644671-dd330165-8d64-4449-9a89-92157503b416.png)

**Comment by H-agha** [comment]
Here is the slides of the suggested cyclic structures for site 3 based on the alignment of the five fragments.
[Cyclic structure site 3-NSP13.pptx](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7677362/Cyclic.structure.site.3-NSP13.pptx)

**Comment by mattodd** [comment]
Closing for now due to more recent effort being focussed on targets arising from modelling, where the structures are unrelated to the fragments (while still being guided by the pharmacophore). This page is clearly linked from the [Story So Far](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/wiki/The-Story-so-Far) page.
