### ISSUE TITLE
Open-Source Coronavirus Monthly Update Meeting #10: 17:00-18:00 BST, Monday 13th March 2023.

### ISSUE THREAD

**Issue by TomkUCL** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#37]
Date: Monday 13th March 2023.
Time: 5pm GMT ([other times](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20230109&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))
Place: https://ucl.zoom.us/j/97172937586
Recording: https://youtu.be/1ZIkm9DaGPc

Previous Meeting: https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/issues/33

Who can come?: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

Attending: @TomkUCL @mattodd @tmw20653 @SumeraMalik123 @KangpingL @ahsgc, Peter brown (UoT), @kipUNC, Alex Tropsha (UNC), @jamesday100, https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13

Slide decks:
Please https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13 remember that if you share slides/info, drag and drop those into a comment on this page, below. Very easy and saves @mattodd having to pester you.

https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13 rough agenda:

Agenda:
1. @kipUNC discussion of outline to discuss the origin of the current list of target compounds (Enamine REAL list of 150 compounds and de-novo generated list of 100 compounds. @TomkUCL can then describe the list analysis and triage based on #15 #17 
2. Discussion of results discussed in Cores meeting, and what is known about confirmed binders @SumeraMalik123 @ahsgc . Possible use as positive controls for the SPR assay given issues with PUG (binding selectivity, irreversible binding, etc.). 
3. @TomkUCL chemistry update on novel mono-Boc protected diamine linkers (see Tom's slides attached in the comments below).

**Comment by TomkUCL** [comment]
Slide deck: [Tom's Deck.pdf](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/10956276/Tom.s.Deck.pdf)

**Comment by mattodd** [comment]
Looks good. We've had some nice suggestions from people in #35. Could we please summarise the suggested structures (SMILES) so that the docking scores could perhaps be checked by @kipUNC or someone else? I'm keen to procure the molecules if we're able to, simply. Any commercially avail?

**Comment by TomkUCL** [comment]
![image](https://user-images.githubusercontent.com/92033163/224755877-59f14010-efdd-45db-872b-87218574d3e9.png)

![image](https://user-images.githubusercontent.com/92033163/224755777-6d05c961-1a21-4ff2-84de-33b4b5f7608f.png)

**Comment by TomkUCL** [comment]
@kipUNC here are the SMILES strings for suggested alternative compounds with shorter synthetic routes for docking. Your original glide scores are shown below the de novo generated compounds for comparison:

FC(N=C1)=CC=C1CC(N[C@H](CC2)CN2C(C=[N+]3[O-])=C(C=C3)[N+]
FC(C=C1)=CC=C1NC(NC2CCN(C(C=[N+]3[O-])=C(C=C3)[N+]([O-])=O)C2)=O
ClC1=CC=C(NC([C@H](CC2)CN2C(C=[N+]3[O-])=C(C=C3)[N+]([O-])=O)=O)C=N1
FC(N=C1)=CC=C1CC(N[C@H](CC2)CN2C(C=[N+]3[O-])=C(C=C3)[N+]([O-])=O)=O

![image](https://user-images.githubusercontent.com/92033163/224786067-1beec630-0d93-4dd2-a19d-756bf5b7eeae.png)

**Comment by mattodd** [comment]
Closing as all files saved to filestore, and all new content has been linked to the wiki so will not be lost. Nothing else needs resolving that is not already part of later meetings.
