### ISSUE TITLE
Open-Source Coronavirus Monthly Update Meeting #11: 17:00-18:00 BST, Monday 12th June 2023.

### ISSUE THREAD

**Issue by TomkUCL** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#39]
**Agenda Open-Source COVID helicase, nsp13, Mon 12th June 2023:**

Date: Monday 12th June 2023.
Time: 5pm BST ([other times](https://www.timeanddate.com/worldclock/meetingtime.html?iso=20230109&p1=43&p2=136&p3=37&p4=771&p5=235&p6=152&p7=770&p8=250&p9=196&p10=240))
Place: https://ucl.zoom.us/j/97172937586
Previous meeting recordings: https://www.youtube.com/@MedChemCoreD-UCLSoP
Previous Meeting Issue: https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/issues/37

Who can come?: Anyone. No need to say anything unless you'd like to. If you'd like to contribute, please join Github.

Attending: @TomkUCL @mattodd @KangpingL, Andy, Rebecka, @HadiaAmahli (UCL) @tmw20653 @SumeraMalik123 @ahsgc, Peter Brown, @kipUNC, Alex Tropsha (UNC), @jamesday100 (Astex). https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13

Slide decks:
Please https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13 remember that if you share slides/info, drag and drop those into a comment on this page, below. Very easy and saves @mattodd having to pester you.

https://github.com/orgs/StructuralGenomicsConsortium/teams/cnp4-nsp13 Here is this meetings agenda:

- 17:00-17:05: Hadia, Alvaro, Rebecka – self-introduction. 

-  17:05-17:10: @jamesday100 – Conference poster on nsp13 inhibitors identified by group in Rome (any resemblance to Ken’s structure i.e., ATP without the ribose?). Any other recent lit reports of inhibitors?

-  17:10-17:15: @tmw20653 - “ATP-like” positive control compound for SPR identified by Ken’s group (structure, any biological data).

- 17:15-17:20: @TomkUCL , @KangpingL, Andy – overall strategy, current chemistry progress, planned chemistry (one slide update). @ahsgc any update from Piramal on building block synthesis. 

-  17:20- 17:30: @kipUNC  – virtual screening design suggestions beyond pyridine-N-oxides / 5-fluoropyridine capping groups, but still based on mono-boc diamine cores provided by Mat/Tom.  

- 17:30-17:45: @TomkUCL  – Docking and Geoff’s MD simulation of pdb 7cxm/ATP/ssRNA relative to the apo-like fragment-bound structure (pdb 5rm9) at c-terminus-b pocket + using 1000 ns MD simulations to search for transient pockets (in collaboration with Geoff Wells @ UCL SoP) + design of 19F ligand-protein NMR assay with Joe’s fragments as controls (in collaboration with Chris Waudby @ UCL SoP) + update on CreoptixWave GCI. 

- 17:45-17:50 Anwar / Peter / Sumera – summary of recent Enamine N-oxide series ATPase and SPR data, current thinking on assay design (e.g. inclusion of ATP/dsDNA/RNA, immobilisation of RNA/DNA vs protein, etc).  

- Concluding remarks.

**Comment by TomkUCL** [comment]
Actionable items:

- Comparison of Glide and Vina binding poses for generative compounds.
- Comparison of the interactions above against five fragment binding poses from Joe at c-terminus-b.

**Comment by TomkUCL** [comment]
Here are the fragment interactions at the c-terminus-b pocket, as well as some of those N-oxides generated through docking with AutoDock Vina at the same pocket. 

[fragment interactions .pdf](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/11727572/fragment.interactions.pdf)

**Comment by TomkUCL** [comment]
Here are my slides:
[Tom MM slides 12th June 2023.pdf](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/11727586/Tom.MM.slides.12th.June.2023.pdf)

**Comment by mattodd** [comment]
Closing. Tom's files will soon by in the shared filestore on Github and the slides have been linked to in the wiki. Nothing new from meeting that is not already covered in Oct meeting.
