### ISSUE TITLE
Trying to install Data Warrior on Mac (MacOs 11.1)

### ISSUE THREAD

**Issue by lindapatio** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#7]
Hi I'm Linda, a final year MPharm student doing my 3 month masters project with Prof Todd. I need to install Datawarrior but I'm having issues with opening the software, the popup (shown below) keeps showing whenever I try to open the app. Would anyone be able to help please? 
@drc007 @edwintse @mattodd 
<img width="258" alt="Screenshot 2021-11-11 at 14 31 04" src="https://user-images.githubusercontent.com/92246733/141315726-e6a894ea-0472-4216-aee3-7f9d599ed82a.png">

**Comment by drc007** [comment]
Hi,

Open “settings” and go to Security and Privacy.

Under “Apps downloaded from” you should see an option open anyway.

This often happens with software not downloaded from the AppStore.

Cheers

Chris

**Comment by mattodd** [comment]
@lindapatio give @drc007 a harder problem next time :)

**Comment by lindapatio** [comment]
@drc007 Ohhh it worked thank you so much! 

@mattodd I'll keep a note of that for future references hahaha

**Comment by lindapatio** [comment]
Hi! I have another question, which unfortunately isn't complicated (I hope). @drc007 would you be able to help me with setting up the Jupyter Notebook please? I think I'm missing the "notebook for docking" in my home page. My username is UCNVLC8

Thanks for your help!

<img width="721" alt="Screenshot 2021-11-11 at 15 09 40" src="https://user-images.githubusercontent.com/92246733/141322077-acc6d668-9344-4dc9-93a7-6aa0a8d50a19.png">

**Comment by drc007** [comment]
This looks like you are running on the UCL cluster? If so you will need to talk to the cluster admin who I think is Frank Otto? @mattodd will probably know.

**Comment by lindapatio** [comment]
@drc007 thank you for your help! I'll send an email to Frank Otto

**Comment by drc007** [comment]
Here you go, both tided up files in pdb format.
[Archive.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7556149/Archive.zip)

**Comment by lindapatio** [comment]
thank you very much sir!

**Comment by lindapatio** [comment]
@drc007 Hi Prof Swain, I've tried to dock but I'm getting errors on jupyter notebook (please see attached PDF), is there a way i can rectify these issues? Also, the SMINA cell disappeared after I ran it, but I'm not sure why. Hope you can help!
[Jupyter notebook issues (1).pdf](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7564564/Jupyter.notebook.issues.1.pdf)

**Comment by drc007** [comment]
@lindapatio Are you running this locally or on the cluster?

**Comment by lindapatio** [comment]
@drc007 I think I'm running this on the cluster. I'm connected to VPN

**Comment by drc007** [comment]
@lindapatio @mattodd  It looks like the environment is not set up correctly, can you check with Frank Otto?

**Comment by lindapatio** [comment]
@drc007 okay sure, I've emailed him.

**Comment by lindapatio** [comment]
Hi @mattodd Jupyter notebook works now! Prof Frank Otto sent me a modified version. I'm currently justifying one of the nature fragments: 5RMM. Please see the pymol session below for the unoptimised version of this analysis: 
- [unoptimsied 5RMM.pse.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7585063/unoptimsied.5RMM.pse.zip)
- there are two potential conformations that bind the same way as the original 5RMM (state 37 and 73), however do I need to find the conformation that perfectly sits on the same position/active site of the original fragment?                                            
- Hi @drc007, would you be able to optimise this file for me please? 
[5RMM_and_NSP13.pdb.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7585047/5RMM_and_NSP13.pdb.zip)

**Comment by drc007** [comment]
@lindapatio Great news about the notebook, I wonder if we need to keep a copy somewhere for other users?

Here is the file
[5RMM_and_NSP13updated.pdb.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7598187/5RMM_and_NSP13updated.pdb.zip)

**Comment by lindapatio** [comment]
@drc007 Apparently the jupyter notebook that was sent to me initially was a universal one that did not work on the UCL cluster. But the modified one from Frank Otto works and I have been in contact with Prof Kiappes who uses this in his programme, so he's aware of the differences for next term when students start using it! 

Here's a copy of the notebook in case you need to put it somewhere on Github:
[ConformationGenerationDocking.ipynb.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7602175/ConformationGenerationDocking.ipynb.zip)

And thank you very much for your help!
