### ISSUE TITLE
Compounds for soaking at Oxford

### ISSUE THREAD

**Issue by edwintse** [StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B#9]
The following 15 compounds will be sent to Joseph Newman at Oxford for soaking. There are 10 Enamine compounds and an additional 5 compounds synthesised by @jemimahaque, @TomkUCL and @edwintse. Two extra compounds are currently in progress by @jemimahaque and @TomkUCL so they may or may not go into this shipment.

![Untitled Wiley-9](https://user-images.githubusercontent.com/18062981/143869899-7ec1a857-13c2-4081-bd9e-15a9cf29c90e.jpeg)

[Oxford Soaking 2021 Chemdraw.zip](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/files/7822797/Oxford.Soaking.2021.Chemdraw.zip)

**Comment by mattodd** [comment]
@edwintse @TomkUCL we need to solve the compound numbering thing for project (not for internal lab books) - I'm looking into it, in terms of what SGC already does. 

Potentially we can use
SGCOCN_XXXXX_YY_ZZ
Where X is the compound ID (used colloquially to refer to the molecule), YY is salt form and ZZ is batch.

We'd then need to open up the relevant compound registration system. Working on that.

**Comment by edwintse** [comment]
Compounds have been shipped off today

**Comment by mattodd** [comment]
Closing. Page linked from [Story So Far](https://github.com/StructuralGenomicsConsortium/CNP4-Nsp13-C-terminus-B/wiki/The-Story-so-Far) page. Note that compound numbering still not sorted, though there is a new compound numbering system being employed by the wider READDI-AViDD project, and the above would need to be added to that system in the long run.
